# west.yml を上書きしてドライバーを変更
cat <<EOF > config/west.yml
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: shnoo
      url-base: https://github.com/shnoo
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: shnoo
      revision: main
  self:
    path: config
EOF

