manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: englmaxi
      url-base: https://github.com/englmaxi
    # ▼▼▼ badjeff が不安定なので、roBa公式の kumamuk に変更 ▼▼▼
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # ▼▼▼ kumamukのリモートを使用。pathは変えずに上書きします ▼▼▼
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main
      path: modules/drivers/zmk-pmw3610-driver
    # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main
      path: modules/drivers/zmk-dongle-display
  self:
    path: config
