manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: englmaxi
      url-base: https://github.com/englmaxi
    # ▼▼▼ 安定している kumamuk を使用 ▼▼▼
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # ▼▼▼ パスを変更して、強制的に新品をダウンロードさせます ▼▼▼
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main
      path: modules/drivers/zmk-pmw3610-driver-fix
    # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main
      path: modules/drivers/zmk-dongle-display
  self:
    path: config
