manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # ▼▼▼ トラックボール用ドライバ（ここが重要！） ▼▼▼
    - name: zmk-pmw3610-driver
      url: https://github.com/badjeff/zmk-pmw3610-driver
      revision: main
    # ▼▼▼ ディスプレイ用ドライバ ▼▼▼
    - name: zmk-dongle-display
      url: https://github.com/englmaxi/zmk-dongle-display
      revision: main
  self:
    path: config
