manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: englmaxi
      url-base: https://github.com/englmaxi
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # ▼▼▼ ここが重要：保存場所(path)をbuild.yamlの指定と一致させます ▼▼▼
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
      path: modules/drivers/zmk-pmw3610-driver
    # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main
      path: modules/drivers/zmk-dongle-display
  self:
    path: config
